### PR TITLE
Quantum sim

### PR DESCRIPTION
**Pull request by baolatranthe**
Merge

### CODE REVIEW

**Comment by baolatranthe** [comment]
Push?

**Review by baolatranthe — COMMENTED** [review]
reviewed

**Review by baolatranthe — COMMENTED** [review]
good

**Review by stickyQuarks — APPROVED** [review]
Go

**Review by stickyQuarks — APPROVED** [review]
Do it

**Review by stickyQuarks — APPROVED** [review]

**Review by stickyQuarks — APPROVED** [review]

**Review by stickyQuarks — APPROVED** [review]
Now?

**Pull request merged**
